### ISSUE TITLE
Hey :)

### ISSUE THREAD

**Issue by ghost** [horsefeedapples/fbla_app#13]
Hey @horsefeedapples,  It is me Shashank Aaryan friend, I was just curious what database service like AWS, GCP or Firebase. I like how you built your app, idk how the code works but I kinda understand. Happy Coding!

**Comment by horsefeedapples** [comment]
I use Firebase's services. The Cloud Firestore as my database, and Firestore Storage to store actual png, jpg, and pdf files

**Comment by shashanke7y** [comment]
ohh ok i use firebase too, I feel like to learn flutter but i am learning python i guess i will finish python and then learn fluter, i like how your code is set up cool work man keep it up! :)

**Comment by horsefeedapples** [comment]
Thanks. Yeah, python is a cool language with a lot of uses i'd definitely recommend learning that. Keep up the good work with web dev :)

**Comment by shashanke7y** [comment]
Thanks man, happy flutter coding 👍  🥇
